jwt:
  CookieName: "beast-cart"
  SecretKey: "beastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKeybeastCartSecretKey"
  ExpirationMs: 86400000

spring:

  datasource:
    url: jdbc:mysql://localhost/product_catalog
    username: app_user
    password: app_user_password

  flyway:
    url: jdbc:mysql://localhost/product_catalog?createDatabaseIfNotExist=true
    user: root
    password: secret
